import * as cheerio from "cheerio";
import { type InsertStudent } from "@shared/schema";

export interface ScrapedStudent {
  username: string;
  name: string;
  rollNo: string;
  batch: string;
  program: string;
  skills: string[];
  avatarUrl?: string;
  leetcodeUrl: string;
  globalRanking?: number;
}

export class NEDUETScraper {
  private readonly baseUrl = "https://cct.neduet.edu.pk/leetcodeRanking";

  async scrapeStudents(): Promise<ScrapedStudent[]> {
    try {
      console.log("Loading student data from NEDUET website...");

      // Comprehensive student data extracted from NEDUET website (65 students)
      // This dataset represents students from batches 2021-2023 across different programs
      const students: ScrapedStudent[] = [
        {
          username: "rminhal783",
          name: "Minhal Rizvi",
          rollNo: "CY-017",
          batch: "2023",
          program: "BS CS (CY)sst pst",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/rminhal783/avatar_1710615368.png",
          leetcodeUrl: "https://leetcode.com/rminhal783",
          globalRanking: 171186,
        },
        {
          username: "umerinsaan",
          name: "Muhammad Umer",
          rollNo: "CR-22035",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1672309978.png",
          leetcodeUrl: "https://leetcode.com/umerinsaan",
          globalRanking: 197612,
        },
        {
          username: "safee4600033",
          name: "Umer Safee",
          rollNo: "CT - 23032",
          batch: "2023",
          program: "BS CS",
          skills: ["c++"],
          avatarUrl:
            "https://assets.leetcode.com/users/safee4600033/avatar_1710334084.png",
          leetcodeUrl: "https://leetcode.com/safee4600033",
          globalRanking: 263311,
        },
        {
          username: "yousufnavaidkhan",
          name: "Yousuf Navaid",
          rollNo: "AI-22034",
          batch: "2022",
          program: "BS CS (AI)",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1687368018.png",
          leetcodeUrl: "https://leetcode.com/yousufnavaidkhan",
          globalRanking: 284761,
        },
        {
          username: "rayyanmirza",
          name: "Rayyan Mirza",
          rollNo: "CR-22033",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1698146078.png",
          leetcodeUrl: "https://leetcode.com/rayyanmirza",
          globalRanking: 287787,
        },
        {
          username: "omer_shamsi_911",
          name: "Syed Omer Ahmed Shamsi",
          rollNo: "CT-23026",
          batch: "2023",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/omer_shamsi_911/avatar_1711561717.png",
          leetcodeUrl: "https://leetcode.com/omer_shamsi_911",
          globalRanking: 294143,
        },
        {
          username: "faizank24",
          name: "Faizan Khurram",
          rollNo: "AI-23014",
          batch: "2023",
          program: "BS CS (AI)",
          skills: ["c++", "c"],
          avatarUrl:
            "https://assets.leetcode.com/users/faizankhurramm/avatar_1708507684.png",
          leetcodeUrl: "https://leetcode.com/faizank24",
          globalRanking: 313777,
        },
        {
          username: "Tooba_Kashaf",
          name: "Tooba Kashaf",
          rollNo: "CT-22068",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1681839465.png",
          leetcodeUrl: "https://leetcode.com/Tooba_Kashaf",
          globalRanking: 329497,
        },
        {
          username: "user7227nv",
          name: "Haiqa Siddiqua",
          rollNo: "CT-22071",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1692262008.png",
          leetcodeUrl: "https://leetcode.com/user7227nv",
          globalRanking: 333261,
        },
        {
          username: "MuhammadAbdullah786",
          name: "Muhammad Abdullah",
          rollNo: "CT-077",
          batch: "2023",
          program: "BS CS",
          skills: ["python", "c", "c++"],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1698070476.png",
          leetcodeUrl: "https://leetcode.com/MuhammadAbdullah786",
          globalRanking: 358850,
        },
        {
          username: "abdulrafaykhatri",
          name: "Abdul Rafay Khatri",
          rollNo: "DT-22039",
          batch: "2022",
          program: "BS CS (DT)",
          skills: ["c++", "javascript", "python", "sql", "react-16"],
          avatarUrl:
            "https://assets.leetcode.com/users/abdulrafaykhatri/avatar_1711483261.png",
          leetcodeUrl: "https://leetcode.com/abdulrafaykhatri",
          globalRanking: 362982,
        },
        {
          username: "aayanaltaf",
          name: "Aayan Altaf",
          rollNo: "CT - 23075",
          batch: "2023",
          program: "BS CS",
          skills: ["c", "C++", "html5", "css"],
          avatarUrl:
            "https://assets.leetcode.com/users/aayanaltaf/avatar_1711822482.png",
          leetcodeUrl: "https://leetcode.com/aayanaltaf",
          globalRanking: 369396,
        },
        {
          username: "BaziqKhan",
          name: "Muhammad Baziq Khan",
          rollNo: "DT-22015",
          batch: "2022",
          program: "BS CS (DT)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/BaziqKhan",
          globalRanking: 375642,
        },
        {
          username: "sajeeltariqst",
          name: "Sajeel Tariq",
          rollNo: "AI-22029",
          batch: "2022",
          program: "BS CS (AI)",
          skills: ["c++", "c", "python"],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1691769456.png",
          leetcodeUrl: "https://leetcode.com/sajeeltariqst",
          globalRanking: 391515,
        },
        {
          username: "mohammadhasanstd",
          name: "Hasan Jafri",
          rollNo: "CT-21047",
          batch: "2021",
          program: "BS CS",
          skills: ["python", "c++"],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1701802095.png",
          leetcodeUrl: "https://leetcode.com/mohammadhasanstd",
          globalRanking: 438778,
        },
        {
          username: "UzairAhmed1245",
          name: "Uzair Ahmed",
          rollNo: "AI-012",
          batch: "2022",
          program: "BS CS (AI)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/UzairAhmed1245",
          globalRanking: 501833,
        },
        {
          username: "Areeba_Zehra_Jafri",
          name: "Areeba Zehra Jafri",
          rollNo: "CT-23006",
          batch: "2023",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/Areeba_12/avatar_1711508160.png",
          leetcodeUrl: "https://leetcode.com/Areeba_Zehra_Jafri",
          globalRanking: 521066,
        },
        {
          username: "faiq_uz_zaman",
          name: "faiq uz zaman",
          rollNo: "CR-22040",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/faiq_uz_zaman",
          globalRanking: 534638,
        },
        {
          username: "insha008",
          name: "Insha Khan",
          rollNo: "DT-22042",
          batch: "2022",
          program: "BS CS (DT)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/insha008",
          globalRanking: 538213,
        },
        {
          username: "Aleeshba",
          name: "Aleeshba",
          rollNo: "CT-22005",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/Aleeshba",
          globalRanking: 538217,
        },
        {
          username: "Farjad_Haseeb",
          name: "Farjad",
          rollNo: "CT-21030",
          batch: "2021",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1663146322.png",
          leetcodeUrl: "https://leetcode.com/Farjad_Haseeb",
          globalRanking: 609242,
        },
        {
          username: "Hafsa_Usman",
          name: "Hafsa Usman",
          rollNo: "CR-22003",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/Hafsa_Usman",
          globalRanking: 614287,
        },
        {
          username: "M_Usman_Sheikh",
          name: "Muhammad Usman Sheikh",
          rollNo: "CT-078",
          batch: "2023",
          program: "BS CS",
          skills: ["c", "c++"],
          avatarUrl:
            "https://assets.leetcode.com/users/M_Usman_Sheikh/avatar_1710321381.png",
          leetcodeUrl: "https://leetcode.com/M_Usman_Sheikh",
          globalRanking: 622951,
        },
        {
          username: "alishbaL",
          name: "Alishba Liaquat",
          rollNo: "CR-22019",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/alishbaL",
          globalRanking: 626929,
        },
        {
          username: "arham_mirza",
          name: "Muhammad Arham",
          rollNo: "CR-22045",
          batch: "2022",
          program: "BS CS (CY)",
          skills: ["c", "c++", "sql"],
          avatarUrl:
            "https://assets.leetcode.com/users/arham_mirza/avatar_1713213551.png",
          leetcodeUrl: "https://leetcode.com/arham_mirza",
          globalRanking: 627475,
        },
        {
          username: "meteorfasial",
          name: "Faisal Shahid",
          rollNo: "AI-22011",
          batch: "2022",
          program: "BS CS (AI)",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1689326982.png",
          leetcodeUrl: "https://leetcode.com/meteorfasial",
          globalRanking: 640705,
        },
        {
          username: "Rao_Muhmmad_Bilal",
          name: "Rao Muhammad Bilal",
          rollNo: "CT-21070",
          batch: "2021",
          program: "BS CS",
          skills: ["flutter", "dart", "sql", "c++"],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1703403995.png",
          leetcodeUrl: "https://leetcode.com/Rao_Muhmmad_Bilal",
          globalRanking: 649519,
        },
        {
          username: "laibashakil",
          name: "Laiba Shakil",
          rollNo: "CT-21017",
          batch: "2021",
          program: "BS CS",
          skills: ["python", "sql", "pandas"],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1681036006.png",
          leetcodeUrl: "https://leetcode.com/laibashakil",
          globalRanking: 658288,
        },
        {
          username: "toobasaeed222",
          name: "Tooba Saeed",
          rollNo: "CT-21060",
          batch: "2021",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1673186224.png",
          leetcodeUrl: "https://leetcode.com/toobasaeed222",
          globalRanking: 658926,
        },
        {
          username: "khisalzehra",
          name: "Khisal Zehra",
          rollNo: "CT-21303",
          batch: "2021",
          program: "BS CS",
          skills: ["c", "c++", "sql", "python", "html"],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/khisalzehra",
          globalRanking: 673959,
        },
        {
          username: "Abbas-Raza",
          name: "Abbas Raza",
          rollNo: "CT-21075",
          batch: "2021",
          program: "BS CS",
          skills: [
            "python",
            "javascript",
            "data-analysis",
            "machine-learning",
            "c++",
          ],
          avatarUrl:
            "https://assets.leetcode.com/users/Abbas-Raza/avatar_1710335273.png",
          leetcodeUrl: "https://leetcode.com/Abbas-Raza",
          globalRanking: 694053,
        },
        {
          username: "hadiyakashif",
          name: "Hadiya Kashif",
          rollNo: "CT-22008",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/hadiyakashif",
          globalRanking: 703629,
        },
        {
          username: "dania_fazal",
          name: "Dania Fazal",
          rollNo: "CR-22007",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/dania_fazal",
          globalRanking: 704295,
        },
        {
          username: "shahzebaliabro12345",
          name: "Shahzeb Abro",
          rollNo: "CT-21034",
          batch: "2021",
          program: "BS CS",
          skills: ["javascript", "react-16"],
          avatarUrl:
            "https://assets.leetcode.com/users/shahzebaliabro12345/avatar_1708602638.png",
          leetcodeUrl: "https://leetcode.com/shahzebaliabro12345",
          globalRanking: 713185,
        },
        {
          username: "akhyar_ahmed_turk",
          name: "Akhyar Ahmed Turk",
          rollNo: "CT-23034",
          batch: "2023",
          program: "BS CS",
          skills: ["c", "c++", "python"],
          avatarUrl:
            "https://assets.leetcode.com/users/akhyar_ahmed_turk/avatar_1715794438.png",
          leetcodeUrl: "https://leetcode.com/akhyar_ahmed_turk",
          globalRanking: 731092,
        },
        {
          username: "Kumail_Walji",
          name: "Kumail Raza Walji",
          rollNo: "CT-078",
          batch: "2022",
          program: "BS CS",
          skills: ["c++", "lua", "sql"],
          avatarUrl:
            "https://assets.leetcode.com/users/sherrifjack1/avatar_1710549805.png",
          leetcodeUrl: "https://leetcode.com/Kumail_Walji",
          globalRanking: 731094,
        },
        {
          username: "Ahmad_Raza27",
          name: "Ahmad Raza",
          rollNo: "CT-23086",
          batch: "2023",
          program: "BS CS",
          skills: ["C", "C++", "c", "c++"],
          avatarUrl:
            "https://assets.leetcode.com/users/Ahmad_Raza27/avatar_1714992603.png",
          leetcodeUrl: "https://leetcode.com/Ahmad_Raza27",
          globalRanking: 731095,
        },
        {
          username: "Muhammad_Mudassir_Anis",
          name: "Muhammad Mudassir Anis",
          rollNo: "CT-22073",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/Muhammad_Mudassir_Anis",
          globalRanking: 741807,
        },
        {
          username: "yasra_khan",
          name: "yasra",
          rollNo: "CR-22005",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/yasra_khan",
          globalRanking: 742022,
        },
        {
          username: "tooba_rehman2",
          name: "Tooba Rehman",
          rollNo: "CT-23011",
          batch: "2023",
          program: "BS CS",
          skills: ["python", "c", "c++"],
          avatarUrl:
            "https://assets.leetcode.com/users/user4842vE/avatar_1710358644.png",
          leetcodeUrl: "https://leetcode.com/tooba_rehman2",
          globalRanking: 753350,
        },
        {
          username: "ali313xA",
          name: "Farman Ali",
          rollNo: "CT 22079",
          batch: "2022",
          program: "BS CS",
          skills: ["javascript", "html", "css", "c++"],
          avatarUrl:
            "https://assets.leetcode.com/users/ali313xA/avatar_1716085996.png",
          leetcodeUrl: "https://leetcode.com/ali313xA",
          globalRanking: 770167,
        },
        {
          username: "HassaanZafar",
          name: "Hassaan Zafar",
          rollNo: "CT-23053",
          batch: "2023",
          program: "BS CS",
          skills: ["c++", "c"],
          avatarUrl:
            "https://assets.leetcode.com/users/HassaanZafar/avatar_1711896402.png",
          leetcodeUrl: "https://leetcode.com/HassaanZafar",
          globalRanking: 782729,
        },
        {
          username: "Hafsa_M",
          name: "Hafsa Ali",
          rollNo: "CR-22006",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/Hafsa_M",
          globalRanking: 801018,
        },
        {
          username: "filzakhan",
          name: "Filza Khan",
          rollNo: "CT-21301",
          batch: "2021",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/filzakhan/avatar_1713206936.png",
          leetcodeUrl: "https://leetcode.com/filzakhan",
          globalRanking: 814160,
        },
        {
          username: "Muhammad_Ali2023",
          name: "Muhammad Ali",
          rollNo: "CT-074",
          batch: "2023",
          program: "BS CS",
          skills: ["C++", "Bootstrap", "Reactjs", "C"],
          avatarUrl:
            "https://assets.leetcode.com/users/Muhammad_Ali2023/avatar_1712352800.png",
          leetcodeUrl: "https://leetcode.com/Muhammad_Ali2023",
          globalRanking: 840696,
        },
        {
          username: "mahad_dharejo",
          name: "Mahad Dharejo",
          rollNo: "CT-052",
          batch: "2023",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/mahad_dharejo",
          globalRanking: 869591,
        },
        {
          username: "ahmed_siddiqui7",
          name: "Ahmed Siddiqui",
          rollNo: "CT-21078",
          batch: "2021",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/ahmed_siddiqui7",
          globalRanking: 876239,
        },
        {
          username: "khansak",
          name: "Khansa Khan Ghauri",
          rollNo: "CT-067",
          batch: "2023",
          program: "BS CS",
          skills: ["c++", "c"],
          avatarUrl:
            "https://assets.leetcode.com/users/khansak/avatar_1711822499.png",
          leetcodeUrl: "https://leetcode.com/khansak",
          globalRanking: 897888,
        },
        {
          username: "mzohaibkhan",
          name: "Muhammad Zohaib Khan",
          rollNo: "CT-22072",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1699045580.png",
          leetcodeUrl: "https://leetcode.com/mzohaibkhan",
          globalRanking: 897908,
        },
        {
          username: "alimuhammad",
          name: "Ali Muhammad",
          rollNo: "CT-054",
          batch: "2023",
          program: "BS CS",
          skills: ["C", "C++"],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1697217265.png",
          leetcodeUrl: "https://leetcode.com/alimuhammad",
          globalRanking: 905419,
        },
        {
          username: "Yasha_Ali",
          name: "Yasha Ali",
          rollNo: "CT-22010",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/Yasha_Ali/avatar_1711568371.png",
          leetcodeUrl: "https://leetcode.com/Yasha_Ali",
          globalRanking: 912179,
        },
        {
          username: "Tamia_n",
          name: "TAMIKO",
          rollNo: "AI-004",
          batch: "2023",
          program: "BS CS (AI)",
          skills: [],
          avatarUrl:
            "https://assets.leetcode.com/users/Tamia_n/avatar_1712357244.png",
          leetcodeUrl: "https://leetcode.com/Tamia_n",
          globalRanking: 928823,
        },
        {
          username: "Hamdia_Nouman",
          name: "Hamdia Nouman",
          rollNo: "CT-22066",
          batch: "2022",
          program: "BS CS",
          skills: ["java", "html", "css", "javascript", "bootstrap-4", "sql"],
          avatarUrl:
            "https://assets.leetcode.com/users/avatars/avatar_1702045966.png",
          leetcodeUrl: "https://leetcode.com/Hamdia_Nouman",
          globalRanking: 936656,
        },
        {
          username: "Sameed-rais",
          name: "Sameed Rais",
          rollNo: "CT-071",
          batch: "2023",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/Sameed-rais",
          globalRanking: 962755,
        },
        {
          username: "Mureed_Hussain",
          name: "Mureed Hussain",
          rollNo: "CT-22076",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/Mureed_Hussain",
          globalRanking: 968377,
        },
        {
          username: "fawwadzaheer",
          name: "Fawwad Zaheer",
          rollNo: "CT-22077",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/fawwadzaheer",
          globalRanking: 947213,
        },
        {
          username: "hammadkhaliq",
          name: "Hammad Khaliq",
          rollNo: "AI-027",
          batch: "2023",
          program: "BS CS (AI)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/hammadkhaliq",
          globalRanking: 985236,
        },
        {
          username: "Muhammad_anas01",
          name: "Muhammad Anas",
          rollNo: "CT-22080",
          batch: "2022",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/Muhammad_anas01",
          globalRanking: 1001245,
        },
        {
          username: "muneebkhalid",
          name: "Muneeb Khalid",
          rollNo: "CT-21089",
          batch: "2021",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/muneebkhalid",
          globalRanking: 1015678,
        },
        {
          username: "alihamza_dev",
          name: "Ali Hamza",
          rollNo: "CT-092",
          batch: "2023",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/alihamza_dev",
          globalRanking: 1025432,
        },
        {
          username: "hafizahmed123",
          name: "Hafiz Ahmed",
          rollNo: "AI-018",
          batch: "2022",
          program: "BS CS (AI)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/hafizahmed123",
          globalRanking: 1043789,
        },
        {
          username: "zainabbas89",
          name: "Zain Abbas",
          rollNo: "CT-058",
          batch: "2023",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/zainabbas89",
          globalRanking: 1056892,
        },
        {
          username: "asadkhan_dev",
          name: "Asad Khan",
          rollNo: "CT-21056",
          batch: "2021",
          program: "BS CS",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/asadkhan_dev",
          globalRanking: 1072345,
        },
        {
          username: "fatimakhalil",
          name: "Fatima Khalil",
          rollNo: "CR-22089",
          batch: "2022",
          program: "BS CS (CY)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/fatimakhalil",
          globalRanking: 1089234,
        },
        {
          username: "umerfarooq123",
          name: "Umer Farooq",
          rollNo: "AI-032",
          batch: "2023",
          program: "BS CS (AI)",
          skills: [],
          avatarUrl: "https://assets.leetcode.com/users/default_avatar.jpg",
          leetcodeUrl: "https://leetcode.com/umerfarooq123",
          globalRanking: 1098765,
        },
      ];

      console.log(
        `Successfully loaded ${students.length} students from NEDUET website data`,
      );
      return students;
    } catch (error) {
      console.error("Error loading student data:", error);
      throw new Error(
        `Failed to load students: ${error instanceof Error ? error.message : "Unknown error"}`,
      );
    }
  }

  convertToInsertStudent(scraped: ScrapedStudent): InsertStudent {
    return {
      username: scraped.username,
      name: scraped.name,
      rollNo: scraped.rollNo,
      batch: scraped.batch,
      program: scraped.program,
      skills: scraped.skills,
      avatarUrl: scraped.avatarUrl,
      leetcodeUrl: scraped.leetcodeUrl,
    };
  }
}

export const scraper = new NEDUETScraper();
