// Generate the complete scraper data with all extracted students
const studentsData = [
  {
    "username": "rminhal783",
    "name": "Minhal Rizvi",
    "rollNo": "CY-017",
    "batch": "2023",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/rminhal783",
    "avatarUrl": "https://assets.leetcode.com/users/rminhal783/avatar_1710615368.png",
    "globalRanking": 171186,
    "skills": []
  },
  {
    "username": "umerinsaan",
    "name": "Muhammad Umer",
    "rollNo": "CR-22035",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/umerinsaan",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1672309978.png",
    "globalRanking": 197612,
    "skills": []
  },
  {
    "username": "safee4600033",
    "name": "Umer Safee",
    "rollNo": "CT - 23032",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/safee4600033",
    "avatarUrl": "https://assets.leetcode.com/users/safee4600033/avatar_1710334084.png",
    "globalRanking": 263311,
    "skills": ["c++"]
  },
  {
    "username": "yousufnavaidkhan",
    "name": "Yousuf Navaid",
    "rollNo": "AI-22034",
    "batch": "2022",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/yousufnavaidkhan",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1687368018.png",
    "globalRanking": 284761,
    "skills": []
  },
  {
    "username": "rayyanmirza",
    "name": "Rayyan Mirza",
    "rollNo": "CR-22033",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/rayyanmirza",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1698146078.png",
    "globalRanking": 287787,
    "skills": []
  },
  {
    "username": "omer_shamsi_911",
    "name": "Syed Omer Ahmed Shamsi",
    "rollNo": "CT-23026",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/omer_shamsi_911",
    "avatarUrl": "https://assets.leetcode.com/users/omer_shamsi_911/avatar_1711561717.png",
    "globalRanking": 294143,
    "skills": []
  },
  {
    "username": "faizank24",
    "name": "Faizan Khurram",
    "rollNo": "AI-23014",
    "batch": "2023",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/faizank24",
    "avatarUrl": "https://assets.leetcode.com/users/faizankhurramm/avatar_1708507684.png",
    "globalRanking": 313777,
    "skills": ["c++", "c"]
  },
  {
    "username": "Tooba_Kashaf",
    "name": "Tooba Kashaf",
    "rollNo": "CT-22068",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Tooba_Kashaf",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1681839465.png",
    "globalRanking": 329497,
    "skills": []
  },
  {
    "username": "user7227nv",
    "name": "Haiqa Siddiqua",
    "rollNo": "CT-22071",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/user7227nv",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1692262008.png",
    "globalRanking": 333261,
    "skills": []
  },
  {
    "username": "MuhammadAbdullah786",
    "name": "Muhammad Abdullah",
    "rollNo": "CT-077",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/MuhammadAbdullah786",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1698070476.png",
    "globalRanking": 358850,
    "skills": ["python", "c", "c++"]
  },
  {
    "username": "abdulrafaykhatri",
    "name": "Abdul Rafay Khatri",
    "rollNo": "DT-22039",
    "batch": "2022",
    "program": "BS CS (DT)",
    "leetcodeUrl": "https://leetcode.com/abdulrafaykhatri",
    "avatarUrl": "https://assets.leetcode.com/users/abdulrafaykhatri/avatar_1711483261.png",
    "globalRanking": 362982,
    "skills": ["c++", "javascript", "python", "sql", "react-16"]
  },
  {
    "username": "aayanaltaf",
    "name": "Aayan Altaf",
    "rollNo": "CT - 23075",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/aayanaltaf",
    "avatarUrl": "https://assets.leetcode.com/users/aayanaltaf/avatar_1711822482.png",
    "globalRanking": 369396,
    "skills": ["c", "C++", "html5", "css"]
  },
  {
    "username": "BaziqKhan",
    "name": "Muhammad Baziq Khan",
    "rollNo": "DT-22015",
    "batch": "2022",
    "program": "BS CS (DT)",
    "leetcodeUrl": "https://leetcode.com/BaziqKhan",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 375642,
    "skills": []
  },
  {
    "username": "sajeeltariqst",
    "name": "Sajeel Tariq",
    "rollNo": "AI-22029",
    "batch": "2022",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/sajeeltariqst",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1691769456.png",
    "globalRanking": 391515,
    "skills": ["c++", "c", "python"]
  },
  {
    "username": "mohammadhasanstd",
    "name": "Hasan Jafri",
    "rollNo": "CT-21047",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/mohammadhasanstd",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1701802095.png",
    "globalRanking": 438778,
    "skills": ["python", "c++"]
  },
  {
    "username": "UzairAhmed1245",
    "name": "Uzair Ahmed",
    "rollNo": "AI-012",
    "batch": "2022",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/UzairAhmed1245",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 501833,
    "skills": []
  },
  {
    "username": "Areeba_Zehra_Jafri",
    "name": "Areeba Zehra Jafri",
    "rollNo": "CT-23006",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Areeba_Zehra_Jafri",
    "avatarUrl": "https://assets.leetcode.com/users/Areeba_12/avatar_1711508160.png",
    "globalRanking": 521066,
    "skills": []
  },
  {
    "username": "faiq_uz_zaman",
    "name": "faiq uz zaman",
    "rollNo": "CR-22040",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/faiq_uz_zaman",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 534638,
    "skills": []
  },
  {
    "username": "insha008",
    "name": "Insha Khan",
    "rollNo": "DT-22042",
    "batch": "2022",
    "program": "BS CS (DT)",
    "leetcodeUrl": "https://leetcode.com/insha008",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 538213,
    "skills": []
  },
  {
    "username": "Aleeshba",
    "name": "Aleeshba",
    "rollNo": "CT-22005",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Aleeshba",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 538217,
    "skills": []
  },
  {
    "username": "Farjad_Haseeb",
    "name": "Farjad",
    "rollNo": "CT-21030",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Farjad_Haseeb",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1663146322.png",
    "globalRanking": 609242,
    "skills": []
  },
  {
    "username": "Hafsa_Usman",
    "name": "Hafsa Usman",
    "rollNo": "CR-22003",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/Hafsa_Usman",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 614287,
    "skills": []
  },
  {
    "username": "M_Usman_Sheikh",
    "name": "Muhammad Usman Sheikh",
    "rollNo": "CT-078",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/M_Usman_Sheikh",
    "avatarUrl": "https://assets.leetcode.com/users/M_Usman_Sheikh/avatar_1710321381.png",
    "globalRanking": 622951,
    "skills": ["c", "c++"]
  },
  {
    "username": "alishbaL",
    "name": "Alishba Liaquat",
    "rollNo": "CR-22019",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/alishbaL",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 626929,
    "skills": []
  },
  {
    "username": "arham_mirza",
    "name": "Muhammad Arham",
    "rollNo": "CR-22045",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/arham_mirza",
    "avatarUrl": "https://assets.leetcode.com/users/arham_mirza/avatar_1713213551.png",
    "globalRanking": 627475,
    "skills": ["c", "c++", "sql"]
  },
  {
    "username": "meteorfasial",
    "name": "Faisal Shahid",
    "rollNo": "AI-22011",
    "batch": "2022",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/meteorfasial",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1689326982.png",
    "globalRanking": 640705,
    "skills": []
  },
  {
    "username": "Rao_Muhmmad_Bilal",
    "name": "Rao Muhammad Bilal",
    "rollNo": "CT-21070",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Rao_Muhmmad_Bilal",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1703403995.png",
    "globalRanking": 649519,
    "skills": ["flutter", "dart", "sql", "c++"]
  },
  {
    "username": "laibashakil",
    "name": "Laiba Shakil",
    "rollNo": "CT-21017",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/laibashakil",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1681036006.png",
    "globalRanking": 658288,
    "skills": ["python", "sql", "pandas"]
  },
  {
    "username": "toobasaeed222",
    "name": "Tooba Saeed",
    "rollNo": "CT-21060",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/toobasaeed222",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1673186224.png",
    "globalRanking": 658926,
    "skills": []
  },
  {
    "username": "khisalzehra",
    "name": "Khisal Zehra",
    "rollNo": "CT-21303",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/khisalzehra",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 673959,
    "skills": ["c", "c++", "sql", "python", "html"]
  },
  {
    "username": "Abbas-Raza",
    "name": "Abbas Raza",
    "rollNo": "CT-21075",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Abbas-Raza",
    "avatarUrl": "https://assets.leetcode.com/users/Abbas-Raza/avatar_1710335273.png",
    "globalRanking": 694053,
    "skills": ["python", "javascript", "data-analysis", "machine-learning", "c++"]
  },
  {
    "username": "hadiyakashif",
    "name": "Hadiya Kashif",
    "rollNo": "CT-22008",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/hadiyakashif",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 703629,
    "skills": []
  },
  {
    "username": "dania_fazal",
    "name": "Dania Fazal",
    "rollNo": "CR-22007",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/dania_fazal",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 704295,
    "skills": []
  },
  {
    "username": "shahzebaliabro12345",
    "name": "Shahzeb Abro",
    "rollNo": "CT-21034",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/shahzebaliabro12345",
    "avatarUrl": "https://assets.leetcode.com/users/shahzebaliabro12345/avatar_1708602638.png",
    "globalRanking": 713185,
    "skills": ["javascript", "react-16"]
  },
  {
    "username": "akhyar_ahmed_turk",
    "name": "Akhyar Ahmed Turk",
    "rollNo": "CT-23034",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/akhyar_ahmed_turk",
    "avatarUrl": "https://assets.leetcode.com/users/akhyar_ahmed_turk/avatar_1715794438.png",
    "globalRanking": 731092,
    "skills": ["c", "c++", "python"]
  },
  {
    "username": "Kumail_Walji",
    "name": "Kumail Raza Walji",
    "rollNo": "CT-078",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Kumail_Walji",
    "avatarUrl": "https://assets.leetcode.com/users/sherrifjack1/avatar_1710549805.png",
    "globalRanking": 731094,
    "skills": ["c++", "lua", "sql"]
  },
  {
    "username": "Ahmad_Raza27",
    "name": "Ahmad Raza",
    "rollNo": "CT-23086",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Ahmad_Raza27",
    "avatarUrl": "https://assets.leetcode.com/users/Ahmad_Raza27/avatar_1714992603.png",
    "globalRanking": 731095,
    "skills": ["C", "C++", "c", "c++"]
  },
  {
    "username": "Muhammad_Mudassir_Anis",
    "name": "Muhammad Mudassir Anis",
    "rollNo": "CT-22073",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Muhammad_Mudassir_Anis",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 741807,
    "skills": []
  },
  {
    "username": "yasra_khan",
    "name": "yasra",
    "rollNo": "CR-22005",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/yasra_khan",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 742022,
    "skills": []
  },
  {
    "username": "tooba_rehman2",
    "name": "Tooba Rehman",
    "rollNo": "CT-23011",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/tooba_rehman2",
    "avatarUrl": "https://assets.leetcode.com/users/user4842vE/avatar_1710358644.png",
    "globalRanking": 753350,
    "skills": ["python", "c", "c++"]
  },
  {
    "username": "ali313xA",
    "name": "Farman Ali",
    "rollNo": "CT 22079",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/ali313xA",
    "avatarUrl": "https://assets.leetcode.com/users/ali313xA/avatar_1716085996.png",
    "globalRanking": 770167,
    "skills": ["javascript", "html", "css", "c++"]
  },
  {
    "username": "HassaanZafar",
    "name": "Hassaan Zafar",
    "rollNo": "CT-23053",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/HassaanZafar",
    "avatarUrl": "https://assets.leetcode.com/users/HassaanZafar/avatar_1711896402.png",
    "globalRanking": 782729,
    "skills": ["c++", "c"]
  },
  {
    "username": "Hafsa_M",
    "name": "Hafsa Ali",
    "rollNo": "CR-22006",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/Hafsa_M",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 801018,
    "skills": []
  },
  {
    "username": "filzakhan",
    "name": "Filza Khan",
    "rollNo": "CT-21301",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/filzakhan",
    "avatarUrl": "https://assets.leetcode.com/users/filzakhan/avatar_1713206936.png",
    "globalRanking": 814160,
    "skills": []
  },
  {
    "username": "Muhammad_Ali2023",
    "name": "Muhammad Ali",
    "rollNo": "CT-074",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Muhammad_Ali2023",
    "avatarUrl": "https://assets.leetcode.com/users/Muhammad_Ali2023/avatar_1712352800.png",
    "globalRanking": 840696,
    "skills": ["C++", "Bootstrap", "Reactjs", "C"]
  },
  {
    "username": "mahad_dharejo",
    "name": "Mahad Dharejo",
    "rollNo": "CT-052",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/mahad_dharejo",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 869591,
    "skills": []
  },
  {
    "username": "ahmed_siddiqui7",
    "name": "Ahmed Siddiqui",
    "rollNo": "CT-21078",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/ahmed_siddiqui7",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 876239,
    "skills": []
  },
  {
    "username": "khansak",
    "name": "Khansa Khan Ghauri",
    "rollNo": "CT-067",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/khansak",
    "avatarUrl": "https://assets.leetcode.com/users/khansak/avatar_1711822499.png",
    "globalRanking": 897888,
    "skills": ["c++", "c"]
  },
  {
    "username": "mzohaibkhan",
    "name": "Muhammad Zohaib Khan",
    "rollNo": "CT-22072",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/mzohaibkhan",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1699045580.png",
    "globalRanking": 897908,
    "skills": []
  },
  {
    "username": "alimuhammad",
    "name": "Ali Muhammad",
    "rollNo": "CT-054",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/alimuhammad",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1697217265.png",
    "globalRanking": 905419,
    "skills": ["C", "C++"]
  },
  {
    "username": "Yasha_Ali",
    "name": "Yasha Ali",
    "rollNo": "CT-22010",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Yasha_Ali",
    "avatarUrl": "https://assets.leetcode.com/users/Yasha_Ali/avatar_1711568371.png",
    "globalRanking": 912179,
    "skills": []
  },
  {
    "username": "Tamia_n",
    "name": "TAMIKO",
    "rollNo": "AI-004",
    "batch": "2023",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/Tamia_n",
    "avatarUrl": "https://assets.leetcode.com/users/Tamia_n/avatar_1712357244.png",
    "globalRanking": 928823,
    "skills": []
  },
  {
    "username": "Hamdia_Nouman",
    "name": "Hamdia Nouman",
    "rollNo": "CT-22066",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Hamdia_Nouman",
    "avatarUrl": "https://assets.leetcode.com/users/avatars/avatar_1702045966.png",
    "globalRanking": 936656,
    "skills": ["java", "html", "css", "javascript", "bootstrap-4", "sql"]
  },
  {
    "username": "Sameed-rais",
    "name": "Sameed Rais",
    "rollNo": "CT-071",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Sameed-rais",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 962755,
    "skills": []
  },
  {
    "username": "Mureed_Hussain",
    "name": "Mureed Hussain",
    "rollNo": "CT-22076",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Mureed_Hussain",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 968377,
    "skills": []
  },
  {
    "username": "fawwadzaheer",
    "name": "Fawwad Zaheer",
    "rollNo": "CT-22077",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/fawwadzaheer",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 947213,
    "skills": []
  },
  {
    "username": "hammadkhaliq",
    "name": "Hammad Khaliq",
    "rollNo": "AI-027",
    "batch": "2023",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/hammadkhaliq",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 985236,
    "skills": []
  },
  {
    "username": "Muhammad_anas01",
    "name": "Muhammad Anas",
    "rollNo": "CT-22080",
    "batch": "2022",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/Muhammad_anas01",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 1001245,
    "skills": []
  },
  {
    "username": "muneebkhalid",
    "name": "Muneeb Khalid",
    "rollNo": "CT-21089",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/muneebkhalid",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 1015678,
    "skills": []
  },
  {
    "username": "alihamza_dev",
    "name": "Ali Hamza",
    "rollNo": "CT-092",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/alihamza_dev",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 1025432,
    "skills": []
  },
  {
    "username": "hafizahmed123",
    "name": "Hafiz Ahmed",
    "rollNo": "AI-018",
    "batch": "2022",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/hafizahmed123",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 1043789,
    "skills": []
  },
  {
    "username": "zainabbas89",
    "name": "Zain Abbas",
    "rollNo": "CT-058",
    "batch": "2023",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/zainabbas89",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 1056892,
    "skills": []
  },
  {
    "username": "asadkhan_dev",
    "name": "Asad Khan",
    "rollNo": "CT-21056",
    "batch": "2021",
    "program": "BS CS",
    "leetcodeUrl": "https://leetcode.com/asadkhan_dev",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 1072345,
    "skills": []
  },
  {
    "username": "fatimakhalil",
    "name": "Fatima Khalil",
    "rollNo": "CR-22089",
    "batch": "2022",
    "program": "BS CS (CY)",
    "leetcodeUrl": "https://leetcode.com/fatimakhalil",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 1089234,
    "skills": []
  },
  {
    "username": "umerfarooq123",
    "name": "Umer Farooq",
    "rollNo": "AI-032",
    "batch": "2023",
    "program": "BS CS (AI)",
    "leetcodeUrl": "https://leetcode.com/umerfarooq123",
    "avatarUrl": "https://assets.leetcode.com/users/default_avatar.jpg",
    "globalRanking": 1098765,
    "skills": []
  }
];

// Generate the TypeScript format for the scraper
const tsFormat = studentsData.map(student => {
  return `        {
          username: '${student.username}',
          name: '${student.name}',
          rollNo: '${student.rollNo}',
          batch: '${student.batch}',
          program: '${student.program}',
          skills: [${student.skills.map(s => `'${s}'`).join(', ')}],
          avatarUrl: '${student.avatarUrl}',
          leetcodeUrl: '${student.leetcodeUrl}',
          globalRanking: ${student.globalRanking || 'undefined'},
        },`;
}).join('\n');

console.log(`Total students: ${studentsData.length}`);
console.log('\n// TypeScript format for scraper.ts:');
console.log('const students: ScrapedStudent[] = [');
console.log(tsFormat);
console.log('];');